version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13.1-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  
  backend:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.backend
    ports:
      - 8000:8543

  frontend:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.frontend
    ports:
      - 8543:80

  bot:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.bot
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data